services:
  - type: web
    name: sof-backend
    runtime: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        value: "12345"
